# Generated by Django 5.0.7 on 2024-07-23 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_offer_code"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Products",
            new_name="Product",
        ),
    ]
